[project]
name = "practical-ai-bootcamp-and-certification-in-7-days"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.3",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
]
